- apps/docs/public/components/context-menu.html
- apps/docs/public/components/page-header.html
- apps/docs/public/components/pagination.html
- apps/docs/public/components/popover.html
- apps/docs/public/components/sub-header.html
- apps/docs/public/components/table.html
- apps/docs/public/components/tag-box.html
- apps/docs/public/components/tooltip.html
- packages/wc-compass/src/styles/_medium.scss
- Fix responsive about section
- Update document
> chore: fix responsive about section and update docs

- .changeset/stupid-dolls-prove.md
- packages/wc-compass/src/components/index.js
- packages/wc-compass/src/components/loading/loading.js
**1) Root cause**
* Applying new font icon caused the problem of wrong alignment without line height css
* Loading indicator wont work without class name because of checking for text option condition
**2) Changes**
* Add line height for icon inside breadcrumbs
* Move add class name statement outside of if condition
**3) Impact**
* All breadcrumbs
* All loading indicators
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Fix for common ui bugs

- .github/pull_request_template.md
- apps/docs/public/services/utilities/index.js
- apps/docs/public/services/utilities/reg-email/reg-email.section.html
- apps/docs/public/services/utilities/reg-email/reg-email.section.js
- apps/docs/public/services/utilities/reg-number/reg-number.section.html
- apps/docs/public/services/utilities/reg-number/reg-number.section.js
- apps/docs/public/services/utilities/reg-phone/reg-phone.section.html
- apps/docs/public/services/utilities/reg-phone/reg-phone.section.js
- apps/docs/public/services/utilities/reg-space/reg-space.section.html
- apps/docs/public/services/utilities/reg-space/reg-space.section.js
- apps/docs/public/services/utilities/reg-text/reg-text.section.html
- apps/docs/public/services/utilities/reg-text/reg-text.section.js
- apps/docs/public/services/utilities/utilities.html
- apps/docs/public/services/utilities/utility/utility.section.html
- packages/wc-compass/src/shared/regex.js
**1) Changes**
Add common regex and sample
**2) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-274
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> [CDS-274] Add common regex

- apps/docs/public/components/text-field/text-field.html
- apps/docs/public/dev.html
- apps/docs/public/main.html
- apps/docs/public/sample-section.js
- packages/wc-compass/src/styles/_forms.scss
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Add sample for text-field

- packages/wc-compass/src/layouts/timeline/timeline-card-time.js
- packages/wc-compass/src/styles/_loading.scss
**1) Changes**
Update loading layout
**2) Impact**
No impacts
https://comfortdelgrotaxi.atlassian.net/browse/CDS-292
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> [CDS-292] Update for skeleton loading layout

- apps/docs/public/components/chart/bar-chart/bar-chart.section.html
- apps/docs/public/components/chart/bar-chart/bar-chart.section.js
- apps/docs/public/components/chart/chart.html
- apps/docs/public/components/chart/index.js
- apps/docs/public/components/chart/line-chart/line-chart.section.html
- apps/docs/public/components/chart/line-chart/line-chart.section.js
- apps/docs/public/components/chart/radar-chart/radar-chart.section.html
- apps/docs/public/components/chart/radar-chart/radar-chart.section.js
- packages/wc-compass/package.json
- packages/wc-compass/src/components/chart/_chart.scss
- packages/wc-compass/src/components/chart/chart.js
- pnpm-lock.yaml
**1) Changes**
* Upgrade chartjs newest version
* Add 3 different demo
* Add reference link
**2) Impact**
* No
https://comfortdelgrotaxi.atlassian.net/browse/CDS-280
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> [CDS-280] Add chart demo and code

- apps/docs/public/components/gutter/gutter.html
- packages/wc-compass/src/components/gutter/gutter.js
Gutter - User can resize the child column larger than parent
**1) Changes**
https://comfortdelgrotaxi.atlassian.net/browse/CDS-394
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> [CDS-394] Gutter - User can resize the child column larger than parent

- pnpm-lock.yaml
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Fix: Update pnpm-lock

- apps/docs/public/components/datepicker/datepicker.html
- apps/docs/public/services/validation/datepicker/datepicker-validation.section.html
- apps/docs/public/services/validation/datepicker/datepicker-validation.section.js
- packages/wc-compass/src/components/datepicker/_datepicker.scss
- packages/wc-compass/src/components/datepicker/datepicker.js
- packages/wc-compass/src/styles/_forms.scss
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Refactor datepicker html structure

- .changeset/odd-buses-rescue.md
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Add changeset for build version

- packages/wc-compass/src/components/floating-content/floating-content.js
- packages/wc-compass/src/components/popover/popover.js
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Fixed content with its anchor

- .changeset/silly-ants-help.md
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Release new version

- .changeset/silly-ants-help.md
- packages/wc-compass/src/components/floating-content/floating-content.js
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Release fix floatting content

- apps/docs/public/components/icon/icon-list.js
- apps/docs/public/components/icon/icon-sample.js
- apps/docs/public/components/icon/icon.html
- apps/docs/public/components/icon/icon.js
- apps/docs/public/styles/styles.css
- packages/wc-compass/src/components/icon/icon.js
- packages/wc-compass/src/shared/base-component.js
- packages/wc-compass/src/shared/dom.js
**1) Changes**
Add feature to filter icon
**2) Impact**
https://comfortdelgrotaxi.atlassian.net/browse/CDGPMG-2958
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> [CDGPMG-2958] Add new feature to filter icons

- packages/wc-compass/src/layouts/wizards/wizard-step.js
- packages/wc-compass/src/layouts/wizards/wizards.js
**1) Changes**
Auto clean up old data and update new data when user change the steps list
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Auto cleanup and update items when user changed data list

- apps/docs/public/services/scroll-to-load/grid/grid.section.html
- apps/docs/public/services/scroll-to-load/grid/grid.section.js
- apps/docs/public/services/scroll-to-load/listview/listview.section.html
**1) Changes**
Remove event listener when grid component has been disconnected to the DOM
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Cleanup event listeners when grid section has been disconnected

- packages/wc-compass/src/layouts/image-viewer/group-image-viewer.js
- packages/wc-compass/src/layouts/image-viewer/image-viewer.js
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Update image viewer zoom behavior

- apps/docs/public/bundled/services/form.section.html
- apps/docs/public/components/layouts/layouts.html
- apps/docs/public/components/layouts/layouts.js
- apps/docs/public/services/validation/form/form.section.js
- packages/wc-compass/src/styles/_layouts.scss
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Add more sample to layout

- packages/wc-compass/src/components/list-view/_list-view.scss
- packages/wc-compass/src/components/list-view/list-item.js
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> fix: Cannot drag on mobile

- apps/docs/public/components/wizards/wizards.html
- packages/wc-compass/src/layouts/wizards/_wizards.scss
**1) Changes**
Add readonly state to wizards
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Add readonly state to wizards

- packages/wc-compass/src/components/datepicker/_datepicker.scss
- packages/wc-compass/src/components/datepicker/datepicker.js
- packages/wc-compass/src/components/dropdown/_dropdown.scss
- packages/wc-compass/src/components/dropdown/dropdown-select.js
- packages/wc-compass/src/components/floating-content/_floating-content.scss
- packages/wc-compass/src/components/rating/rating.js
- packages/wc-compass/src/styles/_animate.scss
**1) Changes**
Update dropdown animation
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Update dropdown animation

- apps/docs/public/components/otp/long/long-otp.section.html
- apps/docs/public/components/otp/long/long-otp.section.js
- apps/docs/public/components/otp/short/short-otp.section.html
- apps/docs/public/components/otp/short/short-otp.section.js
- packages/wc-compass/src/form-controls/otp/otp.js
**1) Changes**
Display numeric keyboard for number mode
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Display numeric keyboard for number mode

- .changeset/eighty-countries-wonder.md
**1) Changes**
**2) Impact**
```
(1)
```
```
(2)
WRONG: el, elm
RIGHT: element
```
> Release bug fixing
